#FROM debian:buster
#FROM dockershelf/debian
FROM debian:buster

RUN apt-get update && apt-get install -y cowsay fortune
#COPY entrypoint.sh /

#ENTRYPOINT [ "/usr/games/cowsay" ]
#ENTRYPOINT [ "/entrypoint.sh" ]